name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # download/get the code
      - name: Get code
        uses: actions/checkout@v3
      # just for practice Install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      # install the dependencies
      - name: Install dependencies
        # "npm ci" means we are using package-lock.json to install the dependencies 
        run: npm ci
      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."