name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        # we use ${{ ... }} (the expression syntax) to write or use the metadata from GitHub 
        run: echo "${{ toJSON(github) }}"